[package]
cairo-version = "2.6.3"
description = "Common library for Haiko AMM and strategies."
name = "haiko_lib"
version = "2.0.0"
edition = "2023_11"

[tool.snforge]
fuzzer_runs = 30
fuzzer_seed = 88888

[dependencies]
starknet = "2.6.3"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.21.0" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.11.0" }